spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
server:
  port: 8081
redis:
  host: localhost
  port: 6379
  password:
logging:
  level:
    com.linecorp.line: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
app:
  origins: # Optional: also accepts web origins as an allowlist
    - android:aaa-bbb
    - ios:aaa-bbb
    # Web origins
    # - https://example.com
    # - https://staging.example.com
    # For local development only
    # - http://localhost:3000

